# Generated by Django 5.2.8 on 2025-11-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalafo_app', '0003_category_category_name_en_category_category_name_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.BooleanField(default=False),
        ),
    ]
